GET  http://localhost:3001/api/v1/user


###
POST   http://localhost:5000/api/v1/auth/register/
Authorization: JWT_SECRET
Content-Type: application/json
{
    "email":"vuhuyhoang@gmail.com",
    "password":"1235456"
 
}
###
POST   http://localhost:3001/api/v1/auth/login/
Content-Type: application/json
{
    "email":"vuhuyhoang@gmail.com",
    "password":"1235456"
}